export const projects = [
  {
    slug: 'beta.bisnison.com',
    title: 'BisnisOn',
    description: 'Penyedia Layanan SMM',
    banner: '/images/bisnison.png',
    language: 'https://img.icons8.com/plasticine/100/000000/react.png',
  },
  {
    slug: 'tanzglobal.com',
    title: 'Gait Analysis',
    description: 'Artificial Intelligence - Gait Analysis',
    banner: '/images/gait.png',
    language: 'https://img.icons8.com/plasticine/100/000000/react.png',
  },
  {
    slug: 'reaction.chemweekits.com',
    title: 'Reaction',
    description: 'Research of applied chemistry competition',
    banner: '/images/reaction.png',
    language: 'https://img.icons8.com/plasticine/100/000000/react.png',
  },
  {
    slug: 'play.google.com/store/apps/details?id=com.artapuri.absensi',
    title: 'Absensih',
    description: 'Attendance Mobile App',
    banner: '/images/absensih.png',
    language: 'https://img.icons8.com/color/48/000000/flutter.png',
  },
  {
    slug: 'play.google.com/store/apps/details?id=com.bco.radioapp',
    title: 'BCO Radio',
    description: 'Radio Online Mobile App',
    banner: '/images/radiobco.png',
    language: 'https://img.icons8.com/color/48/000000/flutter.png',
  },
  {
    slug: 'play.google.com/store/apps/details?id=com.AsiatulJannahAlbantani.kamus3bahasa',
    title: 'Kamus 3 Bahasa',
    description: 'Dictionary Mobile App',
    banner: '/images/kamus3bahasa.png',
    language: 'https://img.icons8.com/color/48/000000/flutter.png',
  },
  {
    slug: 'bco.co.id',
    title: 'BCO Media',
    description: 'Portal Berita',
    banner: '/images/bco.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
  {
    slug: 'justisianews.co.id',
    title: 'Justisia News',
    description: 'Portal Berita',
    banner: '/images/justisianews.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
  {
    slug: 'mnnews.co.id',
    title: 'MN News',
    description: 'Portal Berita',
    banner: '/images/mnnews.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
  {
    slug: 'diazmahakaryasemesta.com',
    title: 'PT. Diaz Mahakarya Semesta',
    description: 'Company Profile',
    banner: '/images/dms.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
  {
    slug: 'artapuri.co.id',
    title: 'PT. Artapuri Digital Mediatama',
    description: 'Company Profile',
    banner: '/images/artapuri.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
  {
    slug: 'inv.co.id',
    title: 'INV',
    description: 'Penyedia Undangan Digital',
    banner: '/images/inv.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
  {
    slug: 'hastakaryatm.com',
    title: 'PT. Hastakarya TM',
    description: 'Company Profile',
    banner: '/images/hastakaryatm.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
  {
    slug: 'sinarmutiarateknindo.com',
    title: 'PT. Sinar Mutiara Teknindo',
    description: 'Company Profile',
    banner: '/images/sinarmutiarateknindo.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
  {
    slug: 'globalheaterindoteknik.co.id',
    title: 'PT. Global Heaterindo Teknik',
    description: 'Company Profile',
    banner: '/images/globalheaterindoteknik.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
  {
    slug: 'oasisteknik.com',
    title: 'PT. Oasis Teknik',
    description: 'Company Profile',
    banner: '/images/oasisteknik.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
  {
    slug: 'chemweekits.com',
    title: 'Chemistry Week ITS - 2022',
    description: 'Landing Page',
    banner: '/images/chemweekits.png',
    language: 'https://img.icons8.com/color/48/000000/wordpress.png',
  },
];
